### ISSUE TITLE
avr-gcc: error: CreateProcess: No such file or directory - firmware.elf

### ISSUE THREAD

**Issue by PrivateRyan94** [jonsag/Marlin-3D-Printer-Firmware#3]
Hi,

I'm trying to compile the Marlin 2.0.7.2 Project with Arduino 1.8.13 for my GT2560 A+ Printer with BLTouch but I'm getting the avr-gcc error for the x.elf file. I've allready tried to compile th project using Visual Studio Code and I'm getting a simmilar error (with "firmware.elf").

Du you have an idea to fix this?

[arduino.log](https://github.com/jonsag/Marlin-3D-Printer-Firmware/files/5913264/arduino.log)

**Comment by jonsag** [comment]
Have you done any changes in the configs as suggested in the [README](https://github.com/jonsag/Marlin-3D-Printer-Firmware/blob/master/README-Marlin-2.0.7.2%2C%20HowTo%20and%20Info.md)?

In particular 

> IF you have the STOCK LCD screen
>Comment out line 2000
>
>//#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
>and uncomment line 1850
>
>#define REPRAP_DISCOUNT_SMART_CONTROLLER

if you don't have the full graphic screen?

I forgot to mention that you must have the [U8glib library](https://www.arduino.cc/reference/en/libraries/u8glib/l) installed, but I see that library mentioned on your log so it looks like you have it.

I really can't tell what your problem is.

Try compiling a [vanilla Marlin](https://github.com/MarlinFirmware/Marlin/archive/2.0.x.zip) or even older versions of it, to rule out anything wrong in my configs.

It's been many years since I compiled anything on a Windoze system, so I have no experience of that,

Compiling on VSCode uses the Arduino IDE installation/compiler (if you use 'Visual Studio Code extension for Arduino'), so it's basically the same thing.
You could try PlatformIO (also available in VSCode), but I haven't tried that myself.

There is a thread on [reprap.org](https://reprap.org/forum/read.php?415,879324,879324) over troubles like yours.
An answer says

> Use vscode with platformio.
>
>Its the only reliable way to compile Marlin under Windows

and he gives a link to [how to do it](https://marlinfw.org/docs/basics/install_platformio_vscode.html).
You could give it a try!

Please report back
/jon

**Comment by PrivateRyan94** [comment]
OK, Problem solved. It was an issue with my windows setup ...
Compiling works well on my Ubuntu 20.10 and Arduino 1.8.13.

But I have a new issue...

Send G28
Receive Error:!! STOP called because of BLTouch error - restart with M999
Error:Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)
Error:!! STOP called because of BLTouch error - restart with M999

You have provided these M280 codes in your guide.
Sadly, my printer does nothing after receiving them. He just said "Receive ok" ...

Do you have an idea?

**Comment by jonsag** [comment]
How is the BLTouch connected? 

If you have the GT2560A+, the BLTouch should be connected on the pins labeled '3D Touch' in this [image](http://www.geeetech.com/wiki/images/thumb/4/40/GT2560A%2B.jpg/700px-GT2560A%2B.jpg).

If you have the older GT2560, and have done the mod described [here](https://www.instructables.com/How-to-Add-Auto-Bed-Leveling-Sensor-to-Geeetech-Pr/), you must also do the firmware changes described there.
This setup is really not covered by my firmware configuration.

If however you have the GT2560A+, I'm thinking you should check your wiring. I really don't know how to measure things up to confirm a correct wiring on the BLTouch. You could send the M280 commmands and see if any values changes on the connections at all...?

Also I'm hoping you got the original BLTouch from [antclabs](https://www.antclabs.com/).
I have very little faith in the Geeetech clone, since I had two of them myself, and had lots of troubles with both.

Let me know how it works out
/jon

**Comment by PrivateRyan94** [comment]
I have the A+ Board and this [BLTouch](https://www.amazon.de/Creality-Verbessertes-Automatische-Bettnivellierungssensoren-Mainboard/dp/B082VSB9VP).

Everything is wired up correctly. I'm using the "3D Touch" and the "Z-Min" pins. I've double checked the pins (+, -, s) but this is correct, too.

With my last firmware, the BLTouch worked fine but I had some other issues in the printing process... So I decided to make a step forward...

Thank you, maybe I'll try it a few more times. I have no idea what's wrong with this printer ... :(
